### ISSUE TITLE
Autodetection of repo and owner 

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pyOpenSourceProjects#4]
if called from the command line owner and repository should be determined if the current directory is a check out / clone of an existing git repository.

see the original bash solution:
```bash
giturl=$(git config --get remote.origin.url)
repo=$(echo $giturl | sed -E 's#http.?://[^/]*/(.*)#\1#')
```

example
```bash
git config --get remote.origin.url
https://github.com/WolfgangFahl/pyOpenSourceProjects
```

**Comment by WolfgangFahl** [comment]
It might also be possible to parse the .git/config file directly:
```
cat config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://github.com/WolfgangFahl/pyOpenSourceProjects
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
```

**Comment by tholzheim** [comment]
Is there a problem with the `--repo` comand that was added with 8fc9bf024d8fc2122545404bad694c4cd9a6c3ea . Or is this some additional functionality.

**Comment by WolfgangFahl** [comment]
This feature was in the bash script so that ideally no command line options are necessary at all if you are in the proper directory. In the migration from the bash script to the python solution its a regression.
